### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by xiamenwcy** [M0rtzz/zzu-resume-template#1]
您好！能否做个overleaf版本呢？

**Comment by M0rtzz** [comment]
> 您好！能否做个overleaf版本呢？

好的，我抽空弄一下

**Comment by M0rtzz** [comment]
> 您好！能否做个overleaf版本呢？

抱歉上周没看见您的信息，刚才已经制作好提交了，overleaf在审核

**Comment by M0rtzz** [comment]
> 您好！能否做个overleaf版本呢？

您好，模板已通过审核：

[Overleaf模板](https://www.overleaf.com/latex/templates/zzu-resume-template/ybncyftnwjhw)
